"""One-shot generator: emits lib/help_center_content_i18n.dart from
`vault_faq_content_i18n.py`. Run manually when translations change.

Usage:
    cd vault_ai_backend
    python _generate_frontend_faq_i18n.py

The script writes exactly one file:
    ../vault_ai_frontend/lib/help_center_content_i18n.dart
"""
from __future__ import annotations

import os
from vault_faq_content import FAQ_ENTRIES, FAQ_CATEGORY_LABELS
from vault_faq_content_i18n import (
    FAQ_TRANSLATIONS,
    FAQ_CATEGORY_LABELS_I18N,
)


NON_ENGLISH = ("ar", "fr", "es", "ja", "ko", "zh")
ALL_LOCALES = ("en",) + NON_ENGLISH


DART_HEADER = """// AUTO-GENERATED by vault_ai_backend/_generate_frontend_faq_i18n.py
// Do not edit by hand. Translations live in
// vault_ai_backend/vault_faq_content_i18n.py and are copied here for
// the Help Center's offline rendering. FAQ IDs and category IDs are
// stable across every locale.

import 'help_center_content.dart'
    show FaqEntry, kFaqEntries, faqEntryById;




const Map<String, Map<String, FaqEntry>> kFaqTranslations = {
"""

DART_FOOTER_TRANSLATIONS = "};\n\n\n"

DART_CATEGORY_HEADER = "const Map<String, Map<String, String>> kFaqCategoryLabelsI18n = {\n"
DART_CATEGORY_FOOTER = "};\n\n\n"

DART_HELPER = """String _normaliseFaqLocale(String? locale) {
  final v = (locale ?? 'en').trim().toLowerCase();
  if (v.isEmpty) return 'en';
  return v.split('-').first;
}


FaqEntry? localizedFaqEntry(String faqId, String? locale) {
  final base = _normaliseFaqLocale(locale);
  final table = kFaqTranslations[base] ?? const <String, FaqEntry>{};
  final hit = table[faqId];
  if (hit != null) return hit;
  final english = kFaqTranslations['en'] ?? const <String, FaqEntry>{};
  final en = english[faqId];
  if (en != null) return en;
  return faqEntryById(faqId);
}


List<FaqEntry> localizedFaqEntries(String? locale) {

  final base = _normaliseFaqLocale(locale);
  final result = <FaqEntry>[];
  for (final canonical in kFaqEntries) {
    result.add(localizedFaqEntry(canonical.id, base) ?? canonical);
  }
  return List<FaqEntry>.unmodifiable(result);
}


List<FaqEntry> localizedFaqEntriesMatchingQuery(
  String? locale,
  String rawQuery,
) {
  final q = rawQuery.trim().toLowerCase();
  final localised = localizedFaqEntries(locale);
  if (q.isEmpty) return localised;
  return localised.where((e) {
    return e.question.toLowerCase().contains(q) ||
        e.answer.toLowerCase().contains(q);
  }).toList(growable: false);
}


String localizedFaqCategoryLabelFor(String categoryId, String? locale) {
  final base = _normaliseFaqLocale(locale);
  final table = kFaqCategoryLabelsI18n[base];
  if (table != null) {
    final label = table[categoryId];
    if (label != null && label.isNotEmpty) return label;
  }
  final english = kFaqCategoryLabelsI18n['en'];
  if (english != null) {
    final label = english[categoryId];
    if (label != null && label.isNotEmpty) return label;
  }
  return categoryId;
}
"""


def dart_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
         .replace("$", r"\$")
         .replace("'", r"\'")
         .replace("\n", r"\n")
    )




def render_translations() -> str:
    out: list[str] = [DART_HEADER]
    for locale in ALL_LOCALES:
        out.append(f"  '{locale}': {{\n")
        if locale == "en":
            for entry in FAQ_ENTRIES:
                q = dart_escape(entry["question"])
                a = dart_escape(entry["answer"])
                out.append(
                    f"    '{entry['id']}': FaqEntry(\n"
                    f"      id: '{entry['id']}',\n"
                    f"      category: '{entry['category']}',\n"
                    f"      question: '{q}',\n"
                    f"      answer: '{a}',\n"
                    f"    ),\n"
                )
        else:
            table = FAQ_TRANSLATIONS.get(locale, {})
            for entry in FAQ_ENTRIES:
                fid = entry["id"]
                localised = table.get(fid, {})
                if not localised.get("question") or not localised.get("answer"):
                    continue
                q = dart_escape(localised["question"])
                a = dart_escape(localised["answer"])
                out.append(
                    f"    '{fid}': FaqEntry(\n"
                    f"      id: '{fid}',\n"
                    f"      category: '{entry['category']}',\n"
                    f"      question: '{q}',\n"
                    f"      answer: '{a}',\n"
                    f"    ),\n"
                )
        out.append("  },\n")
    out.append(DART_FOOTER_TRANSLATIONS)
    return "".join(out)


def render_category_labels() -> str:
    out: list[str] = [DART_CATEGORY_HEADER]
    for locale in ALL_LOCALES:
        table = FAQ_CATEGORY_LABELS_I18N.get(
            locale, FAQ_CATEGORY_LABELS
        )
        out.append(f"  '{locale}': {{\n")
        for cat_id, label in table.items():
            out.append(
                f"    '{cat_id}': '{dart_escape(label)}',\n"
            )
        out.append("  },\n")
    out.append(DART_CATEGORY_FOOTER)
    return "".join(out)


def main() -> None:
    body = render_translations() + render_category_labels() + DART_HELPER
    here = os.path.dirname(os.path.abspath(__file__))
    dst = os.path.normpath(os.path.join(
        here, "..", "vault_ai_frontend", "lib",
        "help_center_content_i18n.dart",
    ))
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print(f"wrote {dst} ({len(body):,} bytes)")


if __name__ == "__main__":
    main()
